trigger: none

variables:
- group: publish-secrets

stages:

- stage: build
  displayName: Build

  jobs:

  - template: templates/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: true
          logs: true
          manifests: true       
      enablePublishUsingPipelines: true
      enablePublishTestResults: true
      enablePublishCodeCoverageResults: true
      
      jobs:
        
      - job: 'Windows'

        pool:
          vmImage: windows-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x86'
            '(Debug) (x64)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x64'
            '(Release) (x86)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x86'
            '(Release) (x64)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x64'

        steps:

          - checkout: self
            submodules: recursive

          - script: .\build.cmd -t -integrationTest -c $(_BuildConfig) -platform $(_BuildPlatform) -pack -ci
            name: build_and_test

      - job: 'Linux'

        pool:
          vmImage: ubuntu-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x86'
            '(Debug) (x64)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x64'
            '(Release) (x86)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x86'
            '(Release) (x64)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x64'
                
        steps:

          - checkout: self
            submodules: recursive

          - script: chmod +x build.sh &&
                    cd eng/common &&
                    chmod +x build.sh &&
                    chmod +x tools.sh
            name: set_execution_permission

          - script: ./build.sh -t --integrationTest -c $CONFIGURATION --platform $PLATFORM --pack --ci
            name: build_and_test
            env:
              CONFIGURATION: $(_BuildConfig)
              PLATFORM: $(_BuildPlatform)
             
      - job: 'MacOS'

        pool:
          vmImage: macos-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x86'
            '(Debug) (x64)':
              _BuildConfig: 'Debug'
              _BuildPlatform: 'x64'
            '(Release) (x86)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x86'
            '(Release) (x64)':
              _BuildConfig: 'Release'
              _BuildPlatform: 'x64'

        steps:

          - checkout: self
            submodules: recursive

          - script: chmod +x build.sh &&
                    cd eng/common &&
                    chmod +x build.sh &&
                    chmod +x tools.sh
            name: set_execution_permission

          - script: ./build.sh -t --integrationTest -c $CONFIGURATION --platform $PLATFORM --pack --ci
            name: build_and_test
            env:
              CONFIGURATION: $(_BuildConfig)
              PLATFORM: $(_BuildPlatform)

- stage: publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: Publish

  dependsOn:
  - build
    
  jobs:

  - template: templates/jobs.yml
    parameters:
      artifacts:
        download:
          name: Artifacts_$(Agent.OS)_Release_x64

      jobs:

      - job: NuGet

        pool:
          vmImage: ubuntu-latest

        steps:

        - task: NuGetCommand@2
          name: sdk
          inputs:
            command: push
            nuGetFeedType: external
            packagesToPush: artifacts/**/MsBullet.Sdk.*.nupkg
            publishFeedCredentials: nuget-connection

      - job: GitHub
        
        pool:
          vmImage: ubuntu-latest

        steps:

        - script: |
            dotnet nuget push "artifacts/**/MsBullet.Sdk.*.nupkg" \
              --api-key $(GITHUB_TOKEN) \
              --source $(GITHUB_NUGET_FEED)
          name: sdk

