name: Bug Report
description: File a bug report
title: "[Bug]: "

labels: 
  - bug
  - triage

assignees:
  - binick

body:

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: macOS Big Sur
      value: operating system
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of MsBullet SDK are you running?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug?
      placeholder: Describe how we can reproduce it
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thank you for reporting the bug! 🙏
