name: Issue
description: Reporting an issue
title: "[Issue]: "

labels: 
  - issue

assignees:
  - binick

body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue encountered
      placeholder: Describe the issue
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: macOS Big Sur
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of MsBullet SDK are you running?
    validations:
      required: false

  - type: markdown
    attributes:
      value: Thank you for reporting the issue! 🙏
