stages:

- stage: build
  displayName: Build
  jobs:
  
  - template: templates/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: true
          logs: true
          manifests: true       
      enablePublishUsingPipelines: true
      enablePublishTestResults: true
      
      jobs:
        
      - job: 'Windows'
      
        pool:
          vmImage: windows-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              configuration: 'Debug'
              platform: 'x86'
            '(Debug) (x64)':
              configuration: 'Debug'
              platform: 'x64'
            '(Release) (x86)':
              configuration: 'Release'
              platform: 'x86'
            '(Release) (x64)':
              configuration: 'Release'
              platform: 'x64'

        steps:

          - script: .\build.cmd -t -integrationTest -c $env:CONFIGURATION -platform $env:PLATFORM -pack -ci
            name: build_and_test
            env:
              CONFIGURATION: $(configuration)
              PLATFORM: $(platform)

      - job: 'Linux'

        pool:
          vmImage: ubuntu-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              configuration: 'Debug'
              platform: 'x86'
            '(Debug) (x64)':
              configuration: 'Debug'
              platform: 'x64'
            '(Release) (x86)':
              configuration: 'Release'
              platform: 'x86'
            '(Release) (x64)':
              configuration: 'Release'
              platform: 'x64'
                
        steps:

          - script: chmod +x build.sh &&
                    cd eng/common &&
                    chmod +x build.sh &&
                    chmod +x tools.sh
            name: set_execution_permission

          - script: ./build.sh -t --integrationTest -c $CONFIGURATION --platform $PLATFORM --pack --ci
            name: build_and_test
            env:
              CONFIGURATION: $(configuration)
              PLATFORM: $(platform)
             
      - job: 'MacOS'

        pool:
          vmImage: macos-latest

        strategy:
          matrix:
            '(Debug) (x86)':
              configuration: 'Debug'
              platform: 'x86'
            '(Debug) (x64)':
              configuration: 'Debug'
              platform: 'x64'
            '(Release) (x86)':
              configuration: 'Release'
              platform: 'x86'
            '(Release) (x64)':
              configuration: 'Release'
              platform: 'x64'

        steps:

          - script: chmod +x build.sh &&
                    cd eng/common &&
                    chmod +x build.sh &&
                    chmod +x tools.sh
            name: set_execution_permission

          - script: ./build.sh -t --integrationTest -c $CONFIGURATION --platform $PLATFORM --pack --ci
            name: build_and_test
            env:
              CONFIGURATION: $(configuration)
              PLATFORM: $(platform)
