name: ci-cd

pool: $(image)

stages:

- stage: ci

  variables:
    jobName: '{0} ({1}) ({2})'
    artifactName: '{1}_{1}_{2}'

  jobs:

  - template: templates/linux-template.yml
    parameters:
      images: [ 'ubuntu:16.04', 'ubuntu:18.04' ]
      configurations: [ 'Debug', 'Release' ]
      platforms: [ 'x86', 'x64' ]

  - template: templates/windows-template.yml
    parameters:
      images: [ 'windows:1903', 'windows:2004' ]
      configurations: [ 'Debug', 'Release' ]
      platforms: [ 'x86', 'x64' ]

  - template: templates/macos-template.yml
    parameters:
      images: [ 'macOS-latest' ]
      configurations: [ 'Debug', 'Release' ]
      platforms: [ 'x86', 'x64' ]
    