name: ci-cd

stages:

- stage: ci

  jobs:
  
    - job: 'Windows'
      strategy:
        matrix:
          '(Debug) (x86)':
            configuration: 'Debug'
            platform: 'x86'
          '(Debug) (x64)':
            configuration: 'Debug'
            platform: 'x64'
          '(Release) (x86)':
            configuration: 'Release'
            platform: 'x86'
          '(Release) (x64)':
            configuration: 'Release'
            platform: 'x64'

      pool:
        vmImage: windows-latest

      steps:
        - script: .\build.cmd -t -integrationTest -c $env:CONFIGURATION -platform $env:PLATFORM -pack -ci
          name: build_and_test
          env:
            CONFIGURATION: $(configuration)
            PLATFORM: $(platform)

    - job: 'Ubuntu'
      strategy:
        matrix:
          '(Debug) (x86)':
            configuration: 'Debug'
            platform: 'x86'
          '(Debug) (x64)':
            configuration: 'Debug'
            platform: 'x64'
          '(Release) (x86)':
            configuration: 'Release'
            platform: 'x86'
          '(Release) (x64)':
            configuration: 'Release'
            platform: 'x64'

      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - script: chmod +x build.sh &&
                  cd eng/common &&
                  chmod +x build.sh &&
                  chmod +x tools.sh
          name: set_execution_permission

        - script: ./build.sh -t -integrationTest -c $CONFIGURATION -platform $PLATFORM -pack -ci
          name: build_and_test
          env:
            CONFIGURATION: $(configuration)
            PLATFORM: $(platform)

    - job: 'MacOS'
      strategy:
        matrix:
          '(Debug) (x86)':
            configuration: 'Debug'
            platform: 'x86'
          '(Debug) (x64)':
            configuration: 'Debug'
            platform: 'x64'
          '(Release) (x86)':
            configuration: 'Release'
            platform: 'x86'
          '(Release) (x64)':
            configuration: 'Release'
            platform: 'x64'

      pool:
        vmImage: 'macos-latest'

      steps:
        - script: chmod +x build.sh &&
                  cd eng/common &&
                  chmod +x build.sh &&
                  chmod +x tools.sh
          name: set_execution_permission

        - script: ./build.sh -t -integrationTest -c $CONFIGURATION -platform $PLATFORM -pack -ci
          name: build_and_test
          env:
            CONFIGURATION: $(configuration)
            PLATFORM: $(platform)
