jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each configuration in parameters.configurations }}:
      - ${{ each platform in parameters.platforms }}:

        - job:

          displayName: '${{ image }} (${{ configuration }}) (${{ platform }})'
          pool:
            vmImage: ubuntu-latest

          container: ${{ image }} 

          steps:

            - script: ./build.sh -t -integrationTest -c $CONFIGURATION -platform $PLATFORM -pack -ci
              env:
                CONFIGURATION: ${{ configuration }}
                PLATFORM: ${{ platform }}
            
            - publish: $(system.defaultworkingdirectory)/artifacts
              artifact: '${{ image }}_${{ configuration }}_${{ platform }}'
