jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each configuration in parameters.configurations }}:
      - ${{ each platform in parameters.platforms }}:

        - job:

          displayName: ${{ format('${{ jobName }}', image, configuration, platform) }}
          pool:
            vmImage: ubuntu-latest

          steps:

            - script: docker run 
                      ${{ image }} 
                      -v '$(system.defaultworkingdirectory)':/msbullet
                      bash -c "cd /msbullet &&
                              ./build.sh -t -integrationTest -c $CONFIGURATION -platform $PLATFORM -pack -ci"
              env:
                CONFIGURATION: ${{ configuration }}
                PLATFORM: ${{ platform }}
            
            - template: publish-common-template.yml
