jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each configuration in parameters.configurations }}:
      - ${{ each platform in parameters.platforms }}:

        - job:

          displayName: '${{ image }} (${{ configuration }}) (${{ platform }})'
          pool:
            vmImage: ${{ image }}

          steps:

            - template: bash-common-template.yml
              parameters:
                - image: ${{ image }}
