jobs:
  - ${{ each configuration in parameters.configurations }}:
    - ${{ each platform in parameters.platforms }}:

      - job:

        displayName: 'windows (${{ configuration }}) (${{ platform }})'
        pool:
          vmImage: windows-latest

        steps:

          - script: .\build.cmd -t -integrationTest -c $env:CONFIGURATION -platform $env:PLATFORM -pack -ci
            name: build_and_test
            env:
              CONFIGURATION: ${{ configuration }}
              PLATFORM: ${{ platform }}
          
          - publish: $(system.defaultworkingdirectory)/artifacts
            artifact: 'windows_${{ configuration }}_${{ platform }}'
            condition: succeededOrFailed()
            
          - task: PublishTestResults@2
            inputs:
              
              testResultsFormat: xUnit
              testResultsFiles: $(system.defaultworkingdirectory)/artifacts/TestResults/${{ configuration }}/*.xml
              buildPlatform: ${{ platform }}
              buildConfiguration: ${{ configuration }}

            condition: succeededOrFailed()
