jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each configuration in parameters.configurations }}:
      - ${{ each platform in parameters.platforms }}:

        - job:

          displayName: ${{ format(variables.jobname, image, configuration, platform) }}
          pool:
            vmImage: windows-latest

          steps:

            - script: docker run 
                      mcr.microsoft.com/${{ image }} 
                      -v '$(system.defaultworkingdirectory)':C:\msbullet
                      cmd /c "cd C:\msbullet &&
                              .\build.cmd -t -integrationTest -c $env:CONFIGURATION -platform $env:PLATFORM -pack -ci"
              env:
                CONFIGURATION: ${{ configuration }}
                PLATFORM: ${{ platform }}
            
            - publish: $(system.defaultworkingdirectory)/artifacts
              artifact: ${{ format(variables.jobname, image, configuration, platform) }}
          
