jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each configuration in parameters.configurations }}:
      - ${{ each platform in parameters.platforms }}:

        - job:

          displayName: '${{ image }} (${{ configuration }}) (${{ platform }})'
          pool:
            vmImage: windows-latest

          steps:

            - script: echo "##vso[task.setvariable variable=prefix]$(env:IMAGE -replace '#|\+|\/|:|@|\[|\/|\]|\^|_|~', '-')" 
              name: evaluate_artifact_name
              env:
                IMAGE: ${{ image }}

            - script: .\build.cmd -t -integrationTest -c $env:CONFIGURATION -platform $env:PLATFORM -pack -ci
              name: build_and_test
              env:
                CONFIGURATION: ${{ configuration }}
                PLATFORM: ${{ platform }}
            
            - template: publish-common-template.yml
              parameters:
                system: $[evaluate_artifact_name.prefix]
                configuration: ${{ configuration }}
                platform: ${{ platform }}
