theme: hugo-theme-learn

params:
  editUrl: https://github.com/binick/msbullet/docs
  themeVariant: green

menu:
  shortcuts:
    - name: "<i class='fab fa-github'></i> Github repo"
      idntifier: ds
      url: https://binick.github.io/msbullet/
