theme: hugo-theme-learn
baseURL: https://binick.github.io/msbullet
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true

params:
  editUrl: https://github.com/binick/msbullet/docs
  themeVariant: green

menu:
  shortcuts:
    - name: "<i class='fab fa-github'></i> Github repo"
      idntifier: ds
      url: https://github.com/binick/msbullet
