name: Build and Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    name: Build and Test on ${{ matrix.os }} (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    strategy:

      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        platform: ['x86', 'x64']
        
        include:
          - os: windows-latest
            run-build: .\build.cmd -t -integrationTest -c Release -platform {0} -pack -ci
          - os: ubuntu-latest
            run-build: ./build.sh -t -integrationTest -c Release -platform {0} -pack -ci    
          - os: macos-latest
            run-build: ./build.sh -t -integrationTest -c Release -platform {0} -pack -ci

    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Set execution permissions for unix.
      - name: Set execution permissions
        run: chmod +x ./build.sh && chmod +x ./eng/common/build.sh && chmod +x ./eng/common/tools.sh
        if: matrix.os != 'windows-latest'

      # Run build and test
      - name: Build and Test
        run: format( ${{ matrix.run-build }}, ${{ matrix.platform }} )

      # Publish artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: sdk-nupkg-${{ matrix.platform }}
          path: '**/artifacts/packages/Release/Shippable/MsBullet.Sdk.*.nupkg'
