name: Build and Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:

      matrix:
        os: [windows-latest]
        
        include:
          - os: windows-latest
            run-build: .\build.cmd -t -integrationTest -c Release


    steps:
      - uses: actions/checkout@v2
      - run: ${{ run-build }}
      - uses: actions/upload-artifact@v2
        with:
          name: sdk-nupgk
          path: '**/artifacts/packages/Release/Shippable/MsBullet.Sdk.*.nupgk'
