name: documentation

on:
  pull_request:
    types: 
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build
        run: |
          mkdir artifacts
          docker run \
            -e "HUGO_ENV=production" \
            -v "$(pwd)/docs:/src" \
            -v "$(pwd)/.git:/src/.git" \
            -v "$(pwd)/artifacts:/artifacts" \
            klakegg/hugo:0.92.2-ext --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOBOT_TOKEN }}
          publish_dir: ./artifacts/tmp/docs
