name: github pages

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
        
      - name: Build
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOBOT_TOKEN }}
          publish_dir: ./docs/public
