name: publish stable version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: true

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
          fetch-depth: 0

      - name: Setup git requirements
        run: |
          git config --local user.email "${{ secrets.AUTOBOT_EMAIL }}"
          git config --local user.name "${{ secrets.AUTOBOT_NAME }}"

      - name: Temporarily disable branch protection
        run: |
          hub api \
          -X PUT \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          /repos/${{ github.repository }}/branches/main/protection \
          --input ./.github/workflows/disable-restrictions.json
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOBOT_TOKEN }}

      - name: Set execution policy to bump-version.ps1 
        run: chmod +x ./eng/bump-version.ps1

      - name: Bump to target version
        run: |
          docker run \
          --mount type=bind,src="$(pwd)",dst=/src \
          mcr.microsoft.com/powershell:lts-alpine-3.10 \
          pwsh -Command "./src/eng/bump-version.ps1 -v '${{ github.event.inputs.version }}'"
      
      - name: Commit stable version
        run: |
          git add version.json \
          && git commit -m "[Bot] Bump version for stable release (${{ github.event.inputs.version }})." \
          && git tag v${{ github.event.inputs.version }} \
          && hub push --tags
        env: 
          GITHUB_TOKEN: ${{ secrets.AUTOBOT_TOKEN }}
        
      - name: Restore pre-release version based on target version
        run: |
          docker run \
          --mount type=bind,src="$(pwd)",dst=/src \
          mcr.microsoft.com/powershell:lts-alpine-3.10 \
          pwsh -Command "./src/eng/bump-version.ps1 -v '${{ github.event.inputs.version }}-beta.{height}' -f"
        
      - name: Commit pre-release version
        run: |
          git add version.json \
          && git commit -m "[Bot] Bump version after stable release (${{ github.event.inputs.version }})." \
          && hub push
        env: 
          GITHUB_TOKEN: ${{ secrets.AUTOBOT_TOKEN }}  

      - name: Enable branch protection
        run: |
          hub api \
          -X PUT \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          /repos/${{ github.repository }}/branches/main/protection \
          --input ./.github/workflows/enable-restrictions.json
        if: always()
        env: 
          GITHUB_TOKEN: ${{ secrets.AUTOBOT_TOKEN }}
