name: publish stable version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: true
      commit:
        description: From (branch, tag or SHA)
        default: master
        required: false

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}
          submodules: true
          fetch-depth: 0

      - name: Setup git requirements
        run: |
          git config --local user.email "${{ secrets.AUTOBOT_EMAIL }}"
          git config --local user.name "${{ secrets.AUTOBOT_NAME }}"

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.AUTOBOT_TOKEN }}
          enforce_admins: false

      - name: Bump to target version
        run: chmod +x ./eng/bump-version.ps1 && docker run --mount type=bind,src="$(pwd)",dst=/src mcr.microsoft.com/powershell:lts-alpine-3.10 pwsh -Command "./src/eng/bump-version.ps1 -v '${{ github.event.inputs.version }}'"
      
      - name: Commit stable version
        run: |
          git add version.json && git commit -m "[Bot] Bump version for stable release (${{ github.event.inputs.version }})."

      - name: Generate tag
        run: git tag v${{ github.event.inputs.version }}
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.AUTOBOT_TOKEN }}
        
      - name: Restore pre-release version based on target version
        run: chmod +x ./eng/bump-version.ps1 && docker run --mount type=bind,src="$(pwd)",dst=/src mcr.microsoft.com/powershell:lts-alpine-3.10 pwsh -Command "./src/eng/bump-version.ps1 -v '${{ github.event.inputs.version }}-beta.{height}' -f"
        
      - name: Commit pre-release version
        run: |
          git add version.json && git commit -m "[Bot] Bump version after stable release (${{ github.event.inputs.version }})."
               
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.AUTOBOT_TOKEN }}
          enforce_admins: true
